### ISSUE TITLE
Can the default configurations be applied as is?

### ISSUE THREAD

**Issue by DennisTheMenace780** [NTBBloodbath/sweetie.nvim#2]
I was trying to work with your colourscheme and I followed the set up instructions, but it seems that my Neovim is not applying the colours in the theme whatsoever. Do we need to apply the colours from the Palette you have provided, or should they load in automatically?

**Comment by NTBBloodbath** [comment]
Hey, this is really strange. Did you enable `termguicolors` Neovim option somewhere in your configuration?

**Comment by DennisTheMenace780** [comment]
Yeah I did have it set to `true` in my `options.lua` file. I did turn it off though, and the same thing still happens. 

Are there any logs I can check/provide that you think might be useful?

**Comment by NTBBloodbath** [comment]
If you can provide a screenshot of the weird behavior and some information of your terminal I think it's going to be useful as sometimes some terminal emulators doesn't work well with colorschemes, for example default MacOS terminal.

**Comment by DennisTheMenace780** [comment]
Yeah this might be the problem then, I am using iTerm2 on MacOS :S
