### ISSUE TITLE
Proper neomake support

### ISSUE THREAD

**Issue by danielb2** [NTBBloodbath/sweetie.nvim#6]
When the line is active, the errors will show fine, but otherwise it's black. See highlight vs not
<img width="608" alt="Screen Shot 2023-05-25 at 08 56 04" src="https://github.com/NTBBloodbath/sweetie.nvim/assets/26678/681cb9d7-b114-4b57-84e5-e0a12460bff3">
<img width="849" alt="Screen Shot 2023-05-25 at 08 55 57" src="https://github.com/NTBBloodbath/sweetie.nvim/assets/26678/bb7cb0e5-f4b6-43df-8d57-4f31ba44e63f">

I would like if the error was red

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply. Seems like my GitHub notifications have had a lot of traffic lately and I've  completely lost this one!

This is odd for me, as all the diagnostics groups have been tested on my side. Are you using an external plugin to see these diagnostics in the screenshot? If so, maybe the plugin does not use the standard highlighting groups and we gotta add its highlighting groups manually to the colorscheme in order to get it working as expected.

Cheers!

**Comment by danielb2** [comment]
hi no worries. The errors are with neomake and rubocop for ruby. 

```
call neomake#configure#automake('w')
let g:neomake_ruby_rubocop_args=['-a', '--force-exclusion', '-D']
```

**Comment by NTBBloodbath** [comment]
Thank you so much for the provided information!

I think it comes from the plugin, not sure why does it links to [spelling highlight groups](https://github.com/neomake/neomake/blob/584f882b9f991245374e7e7d7d1f78bae90b7a35/doc/neomake.txt#L699-L703) but that means we will need to override them and make our own highlighting groups for the plugin.

I will make a small commit once I get some free time today and I will let you know once it's pushed so you can give it a try!

**Comment by NTBBloodbath** [comment]
Finally pushed the changes, can you please pull changes by using your plugin manager and see if the issue persists?

Cheers!

**Comment by danielb2** [comment]
Now it's showing up as black for me instead of white:
<img width="358" alt="Screenshot 2023-06-20 at 3 40 33 PM" src="https://github.com/NTBBloodbath/sweetie.nvim/assets/26678/33917ed0-8d8d-4464-bd21-0cac88826f11">




<img width="470" alt="Screenshot 2023-06-20 at 3 42 00 PM" src="https://github.com/NTBBloodbath/sweetie.nvim/assets/26678/b5f3d707-84ac-4847-9059-f399bc75afbf">

**Comment by NTBBloodbath** [comment]
That's odd, can you please check the output of `:hi NeomakeError`?

**Comment by danielb2** [comment]
<img width="259" alt="Screenshot 2023-06-20 at 3 50 47 PM" src="https://github.com/NTBBloodbath/sweetie.nvim/assets/26678/bbfaa104-aeab-43ec-8111-7445a7e0c29f">

**Comment by NTBBloodbath** [comment]
Right now this is weird ... In theory it should be working as expected as we did modify the plugin highlighting groups.

How could I go about setting up the plugin with a sample code chunk to give it a try? I think that could help me to debug this a bit better

**Comment by danielb2** [comment]
the sample code I'm using is the one in the screenshot

```ruby
def foo
  puts 'blah'
end
end
```
